# !/bin/sh
cat <<PROB
Given that the text file 'input.txt' contains a rectangular block of dot
characters ('.') and two or more hash characters ('#'), write a program 'pather'
which writes out to 'output.txt' the same data with the two '#' characters
joined by asterisks ('*'). The command will be invoked like this:

  pather input.txt output.txt

Your job is to implement 'pather' in this directory. This script will run it
for you and test the accuracy of the output. The file 'pather' will need to
be executable (chmod +x pather). It maybe written in any language.

The rules for the path:

* No diagonals.
* Only change direction once.
* Start with a vertical line and then complete with a horizontal line.

Please feel free to write further tests if you believe the program can be
improved upon. Have fun with it.

PROB

cat <<INPUT >input.txt
........................
........................
....#...................
........................
........................
........................
........................
..................#.....
........................
........................
........................
........................
INPUT

cat <<EXPECTED >expected.txt
........................
........................
....#...................
....*...................
....*...................
....*...................
....*...................
....**************#.....
........................
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input.txt`

Expected Output:

`cat expected.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input.txt output.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output.txt`

Diff:

`diff -u expected.txt output.txt`

CONCLUSION

cat <<INPUT >input-2.txt
........................
........................
....#.............#.....
........................
........................
........................
........................
........................
........................
........................
........................
........................
INPUT

cat <<EXPECTED >expected-2.txt
........................
........................
....#*************#.....
........................
........................
........................
........................
........................
........................
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-2.txt`

Expected Output:

`cat expected-2.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-2.txt output-2.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-2.txt`

Diff:

`diff -u expected-2.txt output-2.txt`

CONCLUSION

cat <<INPUT >input-3.txt
........................
........................
....#.............#.....
........................
........................
........................
........................
........................
............#...........
........................
........................
........................
INPUT

cat <<EXPECTED >expected-3.txt
........................
........................
....#*************#.....
..................*.....
..................*.....
..................*.....
..................*.....
..................*.....
............#******.....
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-3.txt`

Expected Output:

`cat expected-3.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-3.txt output-3.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-3.txt`

Diff:

`diff -u expected-3.txt output-3.txt`

CONCLUSION

cat <<INPUT >input-4.txt
........................
........................
....#.............#.....
........................
........................
........................
........................
........................
.......................#
........................
........................
........................
INPUT


cat <<EXPECTED >expected-4.txt
........................
........................
....#*************#.....
..................*.....
..................*.....
..................*.....
..................*.....
..................*.....
..................*****#
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-4.txt`

Expected Output:

`cat expected-4.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-4.txt output-4.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-4.txt`

Diff:

`diff -u expected-4.txt output-4.txt`

CONCLUSION

cat <<INPUT >input-5.txt
........................
........................
....#...................
........................
........................
....#...................
........................
........................
........................
....#...................
........................
........................
INPUT


cat <<EXPECTED >expected-5.txt
........................
........................
....#...................
....*...................
....*...................
....#...................
....*...................
....*...................
....*...................
....#...................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-5.txt`

Expected Output:

`cat expected-5.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-5.txt output-5.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-5.txt`

Diff:

`diff -u expected-5.txt output-5.txt`

CONCLUSION


cat <<INPUT >input-6.txt
........................
........................
....#...................
.............#..........
........................
........................
....#...................
........................
...........#............
........................
........................
........................
INPUT


cat <<EXPECTED >expected-6.txt
........................
........................
....#...................
....*********#..........
.............*..........
.............*..........
....#*********..........
....*...................
....*******#............
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-6.txt`

Expected Output:

`cat expected-6.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-6.txt output-6.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-6.txt`

Diff:

`diff -u expected-6.txt output-6.txt`

CONCLUSION

cat <<INPUT >input-7.txt
........................
........................
....#...................
.............#.........#
........................
........................
....#...................
........................
...........#............
........................
........................
........................
INPUT

cat <<EXPECTED >expected-7.txt
........................
........................
....#...................
....*********#*********#
.......................*
.......................*
....#*******************
....*...................
....*******#............
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-7.txt`

Expected Output:

`cat expected-7.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-7.txt output-7.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-7.txt`

Diff:

`diff -u expected-7.txt output-7.txt`

CONCLUSION

cat <<INPUT >input-8.txt
........................
........................
....#...................
#............#..........
........................
........................
....#...................
........................
...........#............
........................
........................
........................
INPUT

cat <<EXPECTED >expected-8.txt
........................
........................
....#...................
#************#..........
.............*..........
.............*..........
....#*********..........
....*...................
....*******#............
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-8.txt`

Expected Output:

`cat expected-8.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-8.txt output-8.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-8.txt`

Diff:

`diff -u expected-8.txt output-8.txt`

CONCLUSION

cat <<INPUT >input-9.txt
........................
........................
....#...................
.............#.........#
........................
.............#..........
....#...................
........................
...........#............
........................
........................
........................
INPUT

cat <<EXPECTED >expected-9.txt
........................
........................
....#...................
....*********#*********#
.......................*
.............#**********
....#*********..........
....*...................
....*******#............
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-9.txt`

Expected Output:

`cat expected-9.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-9.txt output-9.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-9.txt`

Diff:

`diff -u expected-9.txt output-9.txt`

CONCLUSION

cat <<INPUT >input-10.txt
........................
........................
....#...................
........................
........................
........................
........................
........................
....#.......#...........
........................
........................
........................
INPUT

cat <<EXPECTED >expected-10.txt
........................
........................
....#...................
....*...................
....*...................
....*...................
....*...................
....*...................
....#*******#...........
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-10.txt`

Expected Output:

`cat expected-10.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-10.txt output-10.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-10.txt`

Diff:

`diff -u expected-10.txt output-10.txt`

CONCLUSION

cat <<INPUT >input-11.txt
...............................
...............................
.......#.......................
...............................
...............................
...............................
...............................
...............................
.......#.......#...............
...............................
...............................
.......#.......................
...............................
...............................
INPUT

cat <<EXPECTED >expected-11.txt
...............................
...............................
.......#.......................
.......*.......................
.......*.......................
.......*.......................
.......*.......................
.......*.......................
.......#*******#...............
...............*...............
...............*...............
.......#********...............
...............................
...............................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-11.txt`

Expected Output:

`cat expected-11.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-11.txt output-11.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-11.txt`

Diff:

`diff -u expected-11.txt output-11.txt`

CONCLUSION

cat <<INPUT >input-12.txt
........................
........................
...........#.......#....
........................
........................
........................
........................
........................
................#..#....
........................
........................
........................
INPUT

cat <<EXPECTED >expected-12.txt
........................
........................
...........#*******#....
...................*....
...................*....
...................*....
...................*....
...................*....
................#**#....
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-12.txt`

Expected Output:

`cat expected-12.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-12.txt output-12.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-12.txt`

Diff:

`diff -u expected-12.txt output-12.txt`

CONCLUSION

cat <<INPUT >input-13.txt
........................
........................
#..........#.......#....
........................
........................
........................
........................
........................
................#..#....
........................
........................
........................
INPUT

cat <<EXPECTED >expected-13.txt
........................
........................
#**********#*******#....
...................*....
...................*....
...................*....
...................*....
...................*....
................#**#....
........................
........................
........................
EXPECTED

cat <<EXPLAIN

Input:

`cat input-13.txt`

Expected Output:

`cat expected-13.txt`
EXPLAIN

if [ -x pather ]; then
  ./pather input-13.txt output-13.txt
else
  echo "PROBLEM: 'pather' does not exist in this directory or is not executable"
fi

cat <<CONCLUSION

Output:

`cat output-13.txt`

Diff:

`diff -u expected-13.txt output-13.txt`

CONCLUSION
